### ISSUE TITLE
Build Swift projects with source dependencies

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#183]
This should include an update to the samples in native-samples.

We want to have a separate external repository to clone in the example.

**Comment by eljobe** [comment]
I've updated the samples in:
https://github.com/gradle/native-samples/compare/c1cfb734bf0f...6d22a8425bb0

Sorry, I didn't bother with a review. We can discuss it more if someone wants.

Next up, I'm going to add an integration test which basically does the same thing that sample does.

**Comment by big-guy** [comment]
I think your samples look good.  I would suggest that we set/use `org.gradle.swift-samples` for the group in all of the builds and in the VCS mappings.  It only accidentally works right now because we assume the root project is the correct project.

**Comment by eljobe** [comment]
So, I've been thinking a lot about the integration test. Essentially, I don't think we should do it. Instead, we should look at getting our samples integrated into our build verification pipeline. There's no reason to have what would basically be two duplicate samples for how to use this feature. I'm going to close this issue as delivered, and file a separate issue that we can deal with later to make it so that our samples run as part of our CI pipeline.

**Comment by big-guy** [comment]
@eljobe could you take a look at this?
