### ISSUE TITLE
Xcode plugin should generate working projects with source dependencies

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#192]
As part of this work, the handling of multi-project, composite build and source dependencies should all use the same code.

**Comment by lacasseio** [comment]
@big-guy Do we want source dependencies to be present in the Xcode project or that auto-completion works from within Xcode project? I don't see a requirement to modify a project that was cloned to disk as part of a source dependencies.

**Comment by adammurdoch** [comment]
There are basically 2 options:

1. The library produced for each source dependency is presented as a prebuilt binary. I should get content completion for symbols in that library and I should be able to run and debug executables and tests that are built against that library. I may or may not be able to see the source, but it's not a goal to be able to make changes to that library (otherwise, it's no longer a source dependency, it's an explicitly included build).
2. The library for each source dependency is presented as another source project, just like all the projects for an explicitly included build. I get content completion for symbols in the library, I can run and debug executables and tests that are built against that library, I can see the source and I can make changes in the IDE to that source and see the changes reflected next time I ask the IDE to do something.

I think we should keep a clear distinction between what are currently called "source dependencies", that is the libraries and other things that I need which happen to be distributed in source form but which I have no interest in making changes to, and "included builds", that is the libraries and other things I want to combine together to make changes too. That is, for source dependencies we should go for option 1.

I'm sure there are better names for these things.

**Comment by lacasseio** [comment]
Thanks for the clarification, that's what I was thinking. I will move ahead with option 1 and clean up the detection of multi-build projects.

**Comment by big-guy** [comment]
I'm taking a look @lacasseio

**Comment by lacasseio** [comment]
Looking a bit closer at this and getting code review/discussing, we came to the following conclusions:
1) Generated source files will be handled in a [separate issue](https://github.com/gradle/gradle-native/issues/166).
2) `IdeaPlugin` will use the same code as part of [another cleanup issue](https://github.com/gradle/gradle/issues/3710). The reason is `IdeaPlugin` (as well as `EclipsePlugin` are similar yet different which easily cause backward compatibility breakage. We need to evaluate the pertinence of such diverging feature and either deprecate them or find better ways around the potential breakage.
3) Source code availability of source dependencies from the IDE will be addressed in a [separate issue](https://github.com/gradle/gradle-native/issues/328).
