### ISSUE TITLE
Enable debugging release builds from XCode

### ISSUE THREAD

**Issue by eljobe** [gradle/gradle-native#214]
As a Swift developer, I expect to be able to debug a swift project I just built in an XCode project which was generated by Gradle, so that I can track down problems more easily.

This is possible in XCode if you create a swift project without generating it with Gradle. But, when the project is using Gradle, you cannot set breakpoints for the release build.

## Implementation
To support this, we'll change the release variant to always compile with debug.  Then after linking we'll extract the debug symbols to a file and strip the debug symbols from the binary.  We'll also add an "optimized" attribute to the configurations so we can accurately resolve the right variant for release.  The extract/strip steps will be implemented as post-link tasks in the pipeline.

## Test Coverage
- Validate that when a release configuration is built from xcode, a symbol file with appropriate debug symbols is produced.
- Validate that the release binary does not have debug symbols.

## Out of Scope
- Doing any of this for software model plugins.
- Any explicit configurability of the symbol extraction or strip tools (such as changing the executable on the toolchain or which symbols should be stripped).
- Any configurability of the binary (such as whether it should be stripped or not).
- Any publishing of the symbol file as an artifact.
- Any compatibility rules around what to do if a dependency does not have an exact match on the debuggable, optimized variant.
- Support in the MSVCPP toolchain - this is just [not really a thing](https://stackoverflow.com/questions/188639/strip-windows-dll-debug-info) in that world.

**Comment by adammurdoch** [comment]
The release variant is intentionally not debuggable. You would use the debug variant instead.

**Comment by lacasseio** [comment]
What could be the expectation of the user? Should Gradle turn on debugging on the release variant automatically when executed through Xcode? Or should it be something the user take action on and turn debugging for his release build?

**Comment by lacasseio** [comment]
The default debugging information is "DWARF with dSYM file" for a release build as opposed to "DWARF" for debug builds.

**Comment by adammurdoch** [comment]
We have a few options.

1. All release builds for all languages are by default debuggable.
2. All release builds for swift are by default debuggable, but not for the other languages.
3. Release builds for all languages are debuggable (if not already) only when built from Xcode.
4. Release builds are by default not debuggable, but it is easy for build logic to enable this
    1. By tweaking the release variant compiler/linker args (this one is already possible).
    2. By adding a new 'debuggable release' variant. The Xcode plugin might use this to implement the option 3 above.
    3. By applying a convention plugin of some kind.

For now, people can tweak the release variant compiler/linker args to make this work.

**Comment by lacasseio** [comment]
According to how Xcode drive a build, option 2 would most likely be the default for Swift.

**Comment by adammurdoch** [comment]
We shouldn't do option 2. It was listed there for discussion so we could say "don't do this one". Release builds should work consistently regardless of the language.

**Comment by ghale** [comment]
I think option 3 here is the way to go.  The only time this behavior is needed is when a build is triggered from Xcode and in that case we want it to "just work" the way the user expects it to.

## Implementation
There are a few options to how this could work.  

1. The simplest solution would be to just trigger off the execution of an xcode build task rule (i.e. "_xcode_*").  When we see this on the task graph, we change any compile tasks to be debuggable.  The downside of this is that we set the compile task to be debuggable very late, possibly preventing configuration rules that might alter the configuration based on whether a compile task is debuggable or not.
1. Another approach would be to set a project property during an xcode build.  The xcode plugin then registers a configuration rule that sets any compile tasks to be debuggable when the project property is present.  This has the advantage that we change the task configuration early enough that other rules can still react to it. 
1. Similar to above, we could trigger off of one of the environment variables (e.g. PRODUCT_NAME) that are set when xcode runs a build.  When the environment variable is set, then the xcode plugin registers a configuration rule to set set compile tasks to be debuggable.

A variation of any of the above is that instead of configuring the compile tasks, we set the debuggable property of the binary.  This would require changing the debuggable flag on the binary to be a `Provider` type and changing the compile tasks accordingly.  However, I'm not sure that this has a ton of value at the moment outside of this story (although it might when we start providing a way for the user to create their own variants).

I think in this case the simplest solution (1 above) is the probably the best one.

## Test Coverage
- Validate that when release and debug configurations are built with xcode, the resulting binary is debuggable.
- Validate that when the xcode plugin is applied, but a release binary is built outside of xcode, it is not debuggable.

**Comment by big-guy** [comment]
@ghale Should we do more to separate out the "built-for-xcode" from the other outputs?

If we change the configuration when we detect that Xcode is driving us, you would have this kind of situation:

1. I do a build from the command-line to build everything.  It takes >1 minute and it finds some failures (debuggable = false).
1. I switch to Xcode and try to debug a particular application.  Gradle is kicked off and rebuilds everything (another >1 minute build because debuggable = true). 
1. I fix the problems and switch back to the command-line to build everything.  Everything rebuilds again (debuggable = false again).

What's not clear to me is where this debugging is started on the release build?  Would we build  for release from the command-line and then try to run that application and connect to it via Xcode?  Or would we build for release and run the application from Xcode?  How do you tell Xcode to connect to it?

There's also a transitivity question.  If I say "build App for Release" in Xcode and App depends on LibFoo and LibBar, I think we'll currently get the release variants of those libs too.  So we would need to enable debuggable for those libraries as well.

Daniel mentions that there are two different kinds of "debuggable" flags.  One is DWARF (where the .o files have the debugging information) and the other is DWARF with dSym.  Which do we need or does it not matter?

**Comment by lacasseio** [comment]
@big-guy is right about the two different kinds of debuggable, however, it should be seen as follow:
1- `-g` flag generate the DWARF debugging symbols which are used for breakpoints in the debugging
2- `dSYM` file is an extra step that takes the binary as input and outputs the `dSYM` file.

The default for Xcode is to always pass `-g` flag for both Debug and Release which allow a developer to use the breakpoint and only do the extra work to generate the `dSYM` file on the release variant.

**Comment by lacasseio** [comment]
It would be good to check if Swift PM has the same behavior as Xcode.

**Comment by ghale** [comment]
> If we change the configuration when we detect that Xcode is driving us, you would have this kind of situation

Hmmm...do you see some way to address the situation you are referring to without making the release builds always debuggable?  That option seems much worse to me...

To me, the point is to get the Gradle-backed configuration to work in Xcode the way the user would expect it to work.  I think that the user is likely to work mostly in Xcode or mostly on the command line but is not likely to be constantly switching back and forth.  If it means that when switching between the command line and xcode, there might be some differences, then I think that's acceptable if it avoids the potentially confusing behavior of Xcode not debugging a release build the way you would expect.  

> What's not clear to me is where this debugging is started on the release build?

What's not clear to me is what you are asking here 😄   Let me restate the problem as I understand it.  When the user sets a breakpoint in Xcode, but selects the release configuration for the scheme, and runs the application, the breakpoint is never reached because Gradle does not build the binary with debug symbols.  If you were to do the same thing with a pure Xcode build (no Gradle), it would work (i.e. breakpoint would be reached).  It doesn't fail or print a warning, it just runs and doesn't reach any breakpoints, which is at the least going to be very confusing to the user.  I'm not aware of any way to remotely debug with Xcode and a quick google did not turn up much (which isn't to say that you can't or wouldn't want to do this - I just don't know how you would do it).  I don't think we should worry about that sort of scenario for this story.

I think transitivity is a very good question.  I wasn't thinking about external dependencies.  We should definitely look into how this is handled with swift PM.

**Comment by adammurdoch** [comment]
I think a strategy where we dynamically toggle the meaning of a variant based on how the user invokes Gradle is not the way to go, as this has all kinds of edge cases. Instead, we should have Xcode build and run a debuggable release variant, that is always debuggable regardless of how the user invokes Gradle.

There are a couple of ways we might do this:

1. Add a new variant, possibly only when Xcode plugin is applied or possibly always.
2. Change the release variant so that it is debuggable, but using separate symbol files.

**Comment by ghale** [comment]
Fair enough.  I like option 2 quite a bit as it could be really useful for other scenarios as well (not just xcode), however I think it becomes problematic on a few levels:

- Near as I can tell, it requires you to build the binary with debug symbols, then to extract the debug symbol table and then strip the debug symbols from the binary.  If there's another way to do this without these extra steps, I've not found it.
- To enable debugging, we have to inhibit any sort of optimization, which creates an awkward scenario for the debug/optimize flags and creates a situation where we have no variant that produces an optimized binary.

I think the separate variant is probably the way to go here.

**Comment by ghale** [comment]
Actually, thinking about this a little bit more, to say that we have to inhibit optimization is not true - we don't _have_ to - in fact, we probably shouldn't.  The fact that the optimizations can make debugging difficult (i.e. due to inlined methods, etc) is probably something the user has already bought into if they are trying to debug the release variant - otherwise why not just debug the debug variant?  In any event, I think the separate variant is still probably the right approach.

I've updated the original description to reflect this approach.

**Comment by adammurdoch** [comment]
right, the debuggable release variant should be exactly the same as the release variant, except debuggable. So, if the release variant is optimised, then the debuggable release variant should be too.

**Comment by ghale** [comment]
So having explored this a little, I think that the separate variant approach may not be the best approach.  The issues are all things that need to be solved eventually, but I'm starting to feel like it might be a lot of complexity in order to push this story over the line, and might be different enough from what people might expect that it will create confusion anyways.  I ran into the following (solvable) issues:

- Ensuring that the debuggable release variant builds as closely as possible to the release variant is awkward.  There are a couple of attributes on the Compile/Link tasks that are not `Provider` objects (for instance the macros map and some of the boolean properties).  
- Everything works great for single project builds, but once we use a multiproject build, it becomes a little more complex.  Because we've set the variant to be debuggable, we then set the debuggable attribute on the configurations, which means we end up getting the debug variant for the upstream project.  To get the debuggable release variant on the upstream project, we'll need to introduce another attribute (e.g. "optimized").  What happens if an upstream project doesn't have the xcode plugin applied (and there is no debuggable, optimized variant)?  We'll certainly have to pick one as the default, but I think there is an argument to be made that either debug or release would be the "correct" default.
- This approach further highlights the awkwardness of our hardcoded approach to variants.  For instance, getting the compile and link tasks (or binary provider objects) is awkward.  It feels like we need some way to query to get the correct binary and/or tasks without having to resort to name-based lookups.

All of these issues are solvable and are things we _should_ solve, but I question whether we should do them _for this story_.  Daniel also brought up the point that the separate variant approach is going to be different from what a typical developer might expect - most developers will expect a stripped binary with separate debug symbols - which is a valid argument.

Initially, the separate debug symbols approach felt wrong to me because we would be doing extra work with every release build that is only needed in certain scenarios.  However, I think the benefits outweigh this.  It has the following qualities:

- It's usable outside of the xcode scenario.
- There isn't a possibility of the configuration being out of sync.
- What "release" means in xcode is the same as what "release" means everywhere.
- Variant resolution continues to work as it does currently.
- We at least don't make the name-based lookup problem worse.

Does anyone feel strongly that the additional variant approach is still the best approach and is worth tackling these other problems in order to finish this story?

**Comment by adammurdoch** [comment]
Changing the release variant so that it is optimized and debuggable (and fixing the other things later) sounds like a reasonable option.

The only thing I would address is add an 'optimized' attribute to the configurations, and set the 'debuggable' attribute to `true` (or actually, whatever value the binary has) for both variants. This means that when I'm building a debug variant, I get a variant of a dependency that is debuggable and _not_ optimized (so I can actually make sense of what the debugger is telling me), and when I'm building a release variant, I get a variant of a dependency that is debuggable and optimized. Later we can add compatibility rules to say "when building the debug variant, if there's no debuggable and unoptimized variant, choose a debuggable variant, then choose anything" and "when building the release variant, if there's no debuggable and optimized variant, then choose an optimized variant (and then fail probably)".

**Comment by ghale** [comment]
I've updated the description to reflect this change in approach.

**Comment by wolfs** [comment]
What would be the effect on caching swift compilation? Would we load/store the debugging information from/to the cache? Would this add some more relocatability constraints on Swift compilation?
We are currently aware that we would need to [normalize the .swiftmodule file](https://github.com/gradle/build-cache/issues/859) for better swift compilation relocatability.
See the [analysis of possible relocatability issues with swift](https://github.com/gradle/build-cache/issues/835).

**Comment by ghale** [comment]
On the surface, I would think the effect would be no different than the effect on the debug variant.  Basically, instead of having the debug symbols and the compiled code in the same file, it would be in two separate files, but generally it's the same information.  Whatever we do for debug variants, we should do for the extracted symbols.

**Comment by ghale** [comment]
There's still some test coverage missing, but this is ready for initial review: https://github.com/gradle/gradle/pull/3563

**Comment by wolfs** [comment]
@ghale We are not doing anything right now for the debug variant. We can do the same for the release variant ;)
More seriously, caching and debugging only works right now if all projects use the same absolute paths. We may want to fix that at some point but we do not have this work scheduled, yet.

**Comment by ghale** [comment]
So after some conversations with @lacasseio, I wanted to document a couple of decisions I made while implementing.  (These could easily be changed if we decide we wanted something different)

- We now create a binary for release that has debug symbols (product of linkRelease) and a stripped binary without debug symbols (product of stripSymbolsRelease).  Libraries currently have a `linkFile` and a `runtimeFile` that are used in different contexts.  We currently use this distinction in the VisualCpp toolchain to provide the ".lib" file at link time (i.e. for linking consuming libraries/executables) and the  ".dll" file at run time (i.e. creating an installation).  For other toolchains these are currently the same file (with these changes, these are now both the stripped version of the library).  One approach we could take is to use this to distinction for cpp and swift libraries such that the link time file is the unstripped binary and the runtime file is the stripped binary.  This has the advantage that when I'm just linking against the library in a multiproject or composite build, I don't have to do the extract/strip steps in order to get the file to link against.  The implication of this, though, is that this information is also used when publishing the binary such that the link file is published with the "link" usage and the runtime file is published with the "runtime" usage, so we would end up publishing two different artifacts (one stripped, one un-stripped) while we currently only publish one.  I chose to simply change as little as possible (i.e. to keep only one publication), but we could potentially make the debuggable binary the link time file to reduce the work necessary for multiproject/composite builds.
- `dsymutil` on MacOS can produce either a flat file or a directory structure when extracting symbols.  Objcopy only produces a flat file.  I'm not aware of any differences between the flat file and directory for `dsymutil`.  I chose to keep the two consistent (i.e. have both produce a flat file), but it's possible that the directory structure is more idiomatic on MacOS (I don't know enough to say one way or the other).  One advantage of the flat file is that if we want to publish this as an artifact, its simpler than having to deal with a directory.

If anyone has any opinions or insight above, I'd welcome any feedback.

**Comment by adammurdoch** [comment]
We should split out an issue to avoid using the stripped binary for linking locally. When building locally against the library, we'd use the output of `linkRelease` for linking (whether that's happening in the same project, for building a test suite, in another project or in another build in the same build tree). When we publish to a repo we'd just publish the stripped binary and consumers would use this for both linking and runtime.

I don't think this is something we need to do right now.

**Comment by ghale** [comment]
@lacasseio I think this is ready for final review (https://github.com/gradle/gradle/pull/3563).

**Comment by lacasseio** [comment]
@ghale I added some comments but it should be good for merging. We can iron out the little details later as I don't know how we could fix them now.

**Comment by ghale** [comment]
@adammurdoch I think I've addressed all of your comments on the PR.
