### ISSUE TITLE
Simplify the output.txt: remove extra useless lines

### ISSUE THREAD

**Issue by zosrothko** [gradle/gradle-native#225]
Hi

Currerntly, the output.txt of compiler is like below 
```
compiling Windows1250Encoding.cpp successful.
Windows1250Encoding.cpp

compiling Windows1251Encoding.cpp successful.
Windows1251Encoding.cpp

compiling Windows1252Encoding.cpp successful.
Windows1252Encoding.cpp

compiling BinaryReader.cpp successful.
BinaryReader.cpp
```
It is useless to state that `compiling Source.cpp successul' while putting the `Source.cpp` name the line below. The skipped line is also useless.

This issue is requesting to remove both and keeing only the source name like below
```
Windows1250Encoding.cpp
Windows1251Encoding.cpp
Windows1252Encoding.cpp
BinaryReader.cpp
```

**Comment by big-guy** [comment]
The line with just the name of the file is coming from the MSVC compiler, but other compilers don't do this (GCC/Clang).  To make the output consistent across compilers, we add the "heading" line.

I don't think we're going to change this because it's useful to be consistent and we'd like to improve the console output over the last resort output file.

**Comment by zosrothko** [comment]
So, could you just put
```
BinaryReader.cpp
```
without a following empty line?
