### ISSUE TITLE
Don't use VisualCpp tool chain if we cannot determine the version of the tool chain

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#256]
If we could not discover the VisualCpp tool chain, we should fail when trying to use the tool chain.

**Comment by ghale** [comment]
Per discussion with @big-guy, I believe this story is about failing when the user configures an installation directory that does not match any installation that we find through our normal discovery.  I believe this is because we want to capture the compiler version so we can publish it in Gradle metadata.

There is at least one scenario where we may want to allow this, though.  With Visual Studio 2017 < update 2, it does not install the `vswhere` executable.  This means that we won't be able to find vswhere, and we won't find the VS2017 install in the registry, so it will essentially be invisible to discovery.  The escape hatch for this was going to be that the user could just configure the install directory.

Options:
1. We just don't support VS2017 < Update 2.
1. We allow VS2017 to be selected (via the installation dir setting) even if we can't discover it.  This should be ok because with VS2017 we can still derive the compiler version from a metadata file in a known location in the directory structure (we can't do this for older versions of visual studio).
1. We support VS2017 < Update 2 by implementing one of the solutions discussed at the end of the comment [here](https://github.com/gradle/gradle-native/issues/34#issuecomment-334797581).

**Comment by lacasseio** [comment]
I would vote for the user providing `vswhere` a [known location](https://github.com/Microsoft/vswhere/issues/41).

**Comment by big-guy** [comment]
@ghale What's the current state of things?  If I specify an installation directory and we wouldn't have found it normally, what do we do?

**Comment by ghale** [comment]
Basically, option 2 above is what we currently do.  As long as we can determine the version of the compiler, we'll accept it (whether we would normally discover it or not).

**Comment by adammurdoch** [comment]
> As long as we can determine the version of the compiler, we'll accept it

Then we're pretty much done. The goal is simply to make sure we never use a VC++ tool chain for which we don't know the version. One way to do that is to fail if we can't discover the installation (and so know the version), but it's not the only way. If we can also somewhat reliably inspect some installations as well, that is also an option. We don't have to be able to inspect any arbitrary installation, just those we can't discover via the registry.

**Comment by ghale** [comment]
Per the discussion, I don't think there's anything more to do here.
