### ISSUE TITLE
Allow Swift components to depend on components exporting a C API

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#287]
### Implementation Checklist
- [ ] **Provide `SWIFT_API` usage in C++ libraries.** Swift and C++ share the `NATIVE_LINK` and `NATIVE_RUNTIME` usage in their dependency declaration. To allow dependency resolution to work out of the box when depending on C++ libraries, `SWIFT_API` usage element should be provided by C++ libraries exposing the `module.modulemap` file to the consumer.
- [ ] **Location of `module.modulemap` is accessible on `CppLibrary`. Add `Provider<RegularFile> getModuleMapFile()` on `CppLibrary`.**
- [ ] **Generate the `module.modulemap` file based on what is present in the exported headers folder.**

### Test cases
- [ ] Swift app depends on C++ library
- [ ] Swift app depends on C++ library A which depends on C++ library B
- [ ] XCTest test suite depends on C++ library
- [ ] XCTest test suite depends on Swift library which depends on C++ library
- [ ] XCTest test suite tests C++ library? (should this even be considered here)
- [ ] Swift library depends on C++ library
- [ ] C++ library with no exported headers doesn't crash (most likely is a no-op)
- [ ] Generated Xcode projects are usable with mixed C++/Swift
- [ ] If I change the modulemap file, does Swift recompile/relink?
- [ ] If I change the C++ headers, does Swift recompile?
- [ ] If I change the C++ sources, does Swift relink?

**Comment by ghale** [comment]
I've done a little investigation into this and I think we should break this story up to keep it manageable.  I propose we bust it into the following stories:

1. We support using a provided module map file in a configurable location (defaults to _publicHeaderDir_/module.modulemap).
1. We support generating the module map file based on some reasonable conventions.
1. Create a native-samples example for mixed swift/c++ projects.

One observation I've made which could be a little problematic is that the headers referenced in the module map file seem to be evaluated relative to the _module map file_ and not to the include path.  This could mean trouble for publishing these module map files as we'll need to recreate the relative directory structure with the public headers on the consuming side or transform the module map file or something else.

**Comment by adammurdoch** [comment]
Sounds like it might _actually_ be better to just generate the map file and do this always. We can see whether anyone actually needs to customise this

**Comment by big-guy** [comment]
We have #288 and #289 for making the modulemap configurable.  I think we don't need to make the location configurable to complete this milestone.  I think it might be OK to have a separate "generate a modulemap" issue.  That would mean that our first implementation would require a user to provide a modulemap at a specific location and fail otherwise. But I think it would be just as easy to try to generate the modulemap.

I think it's a good idea to split out the native-samples part as well because the Swift/C++ interop example should be more interesting than our existing samples. I've already created #317.

I think a generated modulemap file could be dumb initially.  So use absolute paths or relative paths, whichever is easiest.

**Comment by big-guy** [comment]
We can also do #288 to allow someone to provide a custom modulemap (vs the generated one).  This is probably more interesting than being able to configure the source location of the modulemap.

**Comment by ghale** [comment]
Ok, per our discussion, we'll start with an un-configurable generated module map file and we can handle any sort of configurability (in whatever form that takes) in other stories once we understand the use cases we need to support.  We'll still break a native-sample off into its own story.

For the generated module map file, I'm thinking the following:

- We generate a single module definition named after the component itself (i.e. `getBaseName()`).
- All headers in the public headers dir are added to that module.
- We `export *` by default

So, for a component named `foo` with headers `bar.h` and `baz.h`, we would generate the following:
```
module foo {
    header "/some/path/to/bar.h"
    header "/some/path/to/baz.h"
    export *
}
```
Some other options/variations:

- Instead of including each header, we generate an umbrella header that includes all of the public headers.  One advantage of this _might_ be that it could solve the include path issue on publishing that I mentioned above - if we ship the umbrella header around with the module map file, then it can be relative to the module map file, but the headers themselves might be resolved relative to the include path.  I haven't tried this, so it might be wishful thinking.
- Instead of having a single module that pulls in all headers, we treat each header as a submodule, which allows a consumer to pull in the entire module (i.e. `import foo`) or be selective about which headers to import (i.e. `import foo.bar`).  Submodules would be named after the headers, possibly with sub-directories in the name (i.e. `fizz/baz.h` would become module `fizz__baz`).  We would generate something like:
```
module foo {
    module bar {
        header "/some/path/to/bar.h"
        export *
    }
    module fizz__baz {
        header "/some/path/to/fizz/baz.h"
        export *
    }
}
```
- Same as previous, but making submodules explicit, requiring a consumer to always declare the header they want.  This simply removes the "give me everything" usage of the overall module (i.e. it would be more like what you would do when directly including headers in another cpp project).

**Comment by big-guy** [comment]
I believe you can have an umbrella _directory_ too, without having to explicit list every header.

Something like:
```
module foo {
    umbrella "/some/path"
    export *
}
```

I would stay simple and say we export everything and leave submodules for another time.

This makes me think that we may also need a test that has:

C++ libA <- C++ libB <- Swift Lib

Do we need to have modulemaps for both if libA is an API dependency? (I think yes)

**Comment by lacasseio** [comment]
I agree with Sterling, Swift Package Manager generate a `module.modulemap` file like this one:
```
module CSomething {
    umbrella "/path/to/project/Sources/CSomething/include"
    export *
}
```

**Comment by ghale** [comment]
Ah, nice.  Didn't know about that.  Cool, I'll move forward with the simple "importing the module gets everything" approach and an umbrella header that is the public headers directory.

@big-guy With respect to the test case you mentioned above - how is that different from the 2nd test case in the description (or is it the same)?

**Comment by big-guy** [comment]
@ghale You're right, it's the same.  I misread that as a Swift -> Swift -> C++ chain.

**Comment by ghale** [comment]
I still want to polish some of the test coverage a little bit, but this is probably ready for an initial review: https://github.com/gradle/gradle/pull/3766.

**Comment by ghale** [comment]
So there is an aspect of this story that deserves some discussion.  The module map file that we generate is enough for Swift to find all of the headers at compile time.  So, adding the module file directory to the Swift include path is enough to make things work, however, it is not enough to make the `SwiftCompile` task properly incremental.  Meaning, if only the module map file directory is on the include path, then if a header file changes, the consuming `SwiftCompile` task will not recognize a change.  Some ways we could handle this:

1.  Add the public header dirs to the `SWIFT_API` usage and add them to the includes of the `SwiftCompile` task.
1.  Add the public header dirs to the `SWIFT_API` usage and add them as inputs to the `SwiftCompile` task, but do _not_ add them to the includes.
1. Do not add them to the `SWIFT_API` usage and treat them like discovered inputs where we do some sort of parsing of the module map file to find them.

I think ultimately we're going to want to do 3 if we start publishing the module map files, or start handling hand-written module map files.  For this story, I've just done 1 since it is simple and should not have any obvious side effects (for instance, it appears to be common to put the module map file in the public header dir, so it would be normal to have the public header dir on the include path).  It feels a little clunky, though.  My feeling is that it's probably ok for now, and we can handle it more comprehensively (ie tackle option 3 above) when we get to a point where that's necessary.  Does anyone feel like we should do more about this now?

**Comment by ghale** [comment]
@big-guy and I have had some discussions around this and it really seems like doing the module map generation on the consumer side is a better solution (similar to the original idea of doing it with an artifact transform).  Along those lines, I've played around with doing this as part of the `SwiftCompile` task and I've got something mostly working in a spike at https://github.com/gradle/gradle/compare/gh/stable-native/swift-cpp-consumer-side.  Of particular interest is the artifact view and generation of module map information in `DefaultSwiftBinary` as well as the attributes being set on the swift api configuration in `SwiftApplicationPlugin`/`SwiftLibraryPlugin` and `CppLibraryPlugin`.

This basically works by setting a "requires a module map" attribute on the configurations with a `SWIFT_API` usage that say whether or not the configuration requires a module map to be generated in order to be used as a swift dependency.  For Swift modules, the answer is no, but for cpp libraries, the answer is yes.  We then build an artifact view of only the modules with this attribute and use that information to generate module map metadata which is then written as a module map file prior to compilation in the `SwiftCompile` task.  This could just as easily be done as a separate task, too, but it seemed like it might be better if it was just a part of the compile task.

There are still some rough edges in the spike, and we should look at caching the generated module map files to avoid generating them multiple times, but I wanted to put this out there to see if anyone has any feedback or strong objections to this approach.

**Comment by adammurdoch** [comment]
I wouldn't implement this in the compile task, it's not really its responsibility to produce the things that can be used as inputs for compilation. It should just compile stuff. Instead, I'd do this similarly to how we unpack the C++ headers prior to compilation, so that it still looks roughly like an artifact transform and could be replaced by one, which is still the goal. Take a look at https://github.com/gradle/gradle/blob/c51847c3a4a313b8bd3966eedb16753d7abe2385/subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppBinary.java#L162
