### ISSUE TITLE
Configuration should succeed when C++ plugins applied and build run without -Dorg.gradle.internal.experimentalFeatures=true

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#299]
Using the latest from release branch, configuration fails when running a C++ build:

https://e.grdev.net/s/62i6bu7pfigjo

Running with `-Dorg.gradle.internal.experimentalFeatures=true` makes the failure go away, but we shouldn't release 4.4 like this. The flag should only be required for experimental features used by _stable_ plugins, not experimental features used by experimental plugins.

**Comment by big-guy** [comment]
How are our tests not complaining about this?

One of us can look at this on Monday-US if you want to try to do more for #279 for 4.4

**Comment by bigdaz** [comment]
> How are our tests not complaining about this?

I added some basic immutability to the `experimentalFeatures` flag, which means it cannot be enabled after the value was previously read. The bug Adam reports can be triggered by simply running the build with `--scan`, but I suspect that any external plugin resolution will trigger it. This is because we read the `experimentalFeatures` flag when constructing a repository to download plugins, which happens before the `CppPlugin` is applied.

For 4.4, I'll just remove the check that prevents enabling experimental features after the flag has been read. We can come up with a better solution for 4.5.

**Comment by adammurdoch** [comment]
Thanks.

Implementation-wise, I'd probably have multiple internal flags that can be read and enabled separately via internal apis, and a single build option that enables them all. The code would read a specific flag ("publish gradle meta data" or "resolve gradle meta data" etc), the C++ plugin would enable specific flags (publish and resolve), and a user would use the build option via say a Gradle property/system property (which would switch everything on). The read can lock the individual flag.

Regardless of what we come up with, we should look at using `BuildOption` instead of just looking for a magic property to allow the user to enable the features.

**Comment by adammurdoch** [comment]
Actually that's going to have the same problem. We need to be able to resolve plugins and other things with the 'resolve gradle meta-data' flag off, and then switch it on later on some way, if not already, to resolve the native plugin configurations.

**Comment by big-guy** [comment]
@bigdaz thanks! let me know if we can help

**Comment by big-guy** [comment]
Fixed in https://github.com/gradle/gradle/commit/6d6f18751cfabd064473055bb749e6ff1013bcc1
