### ISSUE TITLE
Build logic can declare which linkages to produce for a C++ library

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#349]
- Xcode support
- C++ unit test plugin
- XCTest support
- Swift + C++ interop
- Publishing to a Maven repo

**Comment by big-guy** [comment]
@ghale can you leave a comment here about what's not covered by the milestone issue you're looking at?

**Comment by ghale** [comment]
So #316 covers adding static library support for C++ and Swift/C++ interop.  It necessarily also adds support for static libraries in Xcode and XCTest.  However, there are tests for the swift/c++ interop functionality, but little beyond that.  I would think in order to call that support "done" we would need add a little more significant test coverage for static libraries.

For CppUnit, appropriate changes were made to the CppUnit plugin in order to handle the deferred configuration that was introduced with the static support, and my gut feeling is that it will probably "just work", but no test coverage was added for static libraries.

Nothing was done for publishing or consuming static libraries.  We still only publish the shared library variant and is there no way for a consumer to specify that they want a static library variant in the instance that a cpp dependency can build both static and shared variants.

**Comment by big-guy** [comment]
Let's close this and open a new issue for just the missing test coverage (static and CppUnit)
@ghale

**Comment by ghale** [comment]
#389
