### ISSUE TITLE
C++ Google test sample fails with link error on Ubuntu 17.10

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#377]
Running `./gradlew test` in `cpp/simple-library` fails with a bunch of link errors.

Scan is here: https://scans.gradle.com/s/2bprhrojwabpo

**Comment by big-guy** [comment]
We should republish the Googletest libs with our new CI agents

**Comment by big-guy** [comment]
Address this for the blog post #205

**Comment by donat** [comment]
Hi Folks! [We'd like to migrate](https://github.com/gradle/dev-infrastructure/issues/158) the performance agents to run without virtualization. As discussed on [Slack](https://gradle.slack.com/archives/C5DTC5KGC/p1515764500000168), this issue would make some performance tests fail constantly after the migration. Is there a chance you could priorize the fix?

**Comment by lacasseio** [comment]
It looks like the failure is due to an ordering issue, most likely introduced by some refactorings we recently did. It just happens that the default on the CI server lined up with what was expected so we didn't see the failure. On `dev80`, GCC got bumped to 5.4.0 from 4.8.4. Starting from GCC 5.x, the C++11 ABI got introduced and is the default. To use the old ABI you need to define macro `_GLIBCXX_USE_CXX11_ABI`. The sample correctly defines the macro, however, due to the ordering issue when the configuration code is executed:
```
tasks.withType(CppCompile) {
    if (toolChain instanceof Gcc) {
        compilerArgs.add('-D_GLIBCXX_USE_CXX11_ABI=0')
    }
}
```
The property `toolChain` isn't set yet and is `null`. I will write a small sample and do a git bisect to find what refactoring introduced the issue.

**Comment by lacasseio** [comment]
A fix to the native samples has been [pushed](https://github.com/gradle/native-samples/commit/6641e5cbbb38f1a084ff68be78fadb2751e5490e). It was successfully tested on `dev80`.

@donat It shouldn't be a blocker for the migration of the performance agent.
