### ISSUE TITLE
Visual Studio metadata uses a single solution for multi-project builds

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#410]
Currently, when we generate Visual Studio metadata for a multi-project build, each Gradle component gets a Visual Studio solution that contains the Visual Studio projects for that component as well as any components it depends upon.  We should instead create a single solution for the multi-project build that includes all projects, similar to how we handle this in other ide plugins.

## Implementation Details
- `VisualStudioExtension` will no longer contain solutions, only projects - one per component as we do currently.
- We'll add a VisualStudioSolutionExtension to the root project which will use `registerIdeArtifacts()/getIdeArtifacts()` to track the relationship to child projects.

## Test Coverage
- Generated solution file for a multiproject build contains all components in the root project and subprojects.
- Generated solution file for a single project build contains all components in the project.
- Can generate Visual Studio metadata for a project with no components.
- Correctly handles one or more components in subprojects with the same name.
- Can configure (modify) the root solution file via DSL.

**Comment by lacasseio** [comment]
Do we need to split out VS solution from `VisualStudioExtension` into a separate extension? Could we just leave `VisualStudioExtension#solutions` empty? I fear that removing the solution from the current extension may break builds that have rules already in place to modify the generated solution. The only breaking change will be the behavior change and adjust where the rules are applied (in the root project instead of the child projects), will be an easier fix than using the new extension. We will also need to document that new extension. If we don't need to split it out, I would vote to keep it the way it is and see if the new behavior annoys any developer before making a potentially breaking change.

**Comment by ghale** [comment]
If we leave it as it is, the configuration won't break, it just silently won't do what the user intends.  IMO, this is worse than having a configuration breakage.  If we remove it, at least it will be clear that whatever modification was intended will no longer work.

What we can do is not fail when the solution is modified on `VisualStudioExtension` and just print a deprecation warning basically saying that this is no longer supported and you should move the modification to the root project.

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/4236

@lacasseio can you take a look?

**Comment by ghale** [comment]
Merged.
