### ISSUE TITLE
Add a sample that shows how to consume a C++ library built using cmake

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#424]
An important use case for the native plugins is to allow Gradle builds to use C++ libraries that are built using cmake as source dependencies. This is an important part of the migration story, as I don't have to convert all of my dependencies, or even my own build, to use Gradle before I start using Gradle. It also helps bootstrap the whole C++ dependency management story, as once understood (enough) by Gradle, these binaries can be published somewhere (possibly the build cache).

In theory, it should now be possible, if not particularly convenient, to use a C++ library built using cmake. As a first step towards good support for using cmake-built things we should add a sample showing this in action. It doesn't have to be pretty, later stories will take care of that.

**Comment by ghale** [comment]
Also include Install cmake and ninja on CI machines.

**Comment by big-guy** [comment]
We should link to this sample here once we have it.
https://discuss.gradle.org/t/creating-a-cpp-native-library-from-existing-binaries/25748

**Comment by ghale** [comment]
I've pushed something rough that demonstrates this.  See https://github.com/gradle/native-samples/pull/10.  There is still some polishing to do, but I wanted to go ahead and get some feedback.

Some directions we could go with this:

- Should we split the list and utility libraries into separate zips?  Would this demonstrate anything more than it currently does?
- These are currently static libs, would this be better if they were shared libs?
- We probably want to handle debug and release variants - should we also demonstrate handling OS in the consuming Gradle build since CPack creates an OS-specific package by default?  Or do we want to keep this complication out of the build (ie change the CMake build to generate an OS-agnostic zip file).
- Do we want to include an example of wrapping the CMake build with Gradle?
- I made this so that it uses a configuration to resolve the CMake zip file, but we just add the raw file to the configuration.  Should we instead publish the CMake zip to a local file repo and resolve it from there?
- Are their other things we want to demonstrate with this example?

**Comment by adammurdoch** [comment]
I added a comment to the review. I think it's important to have, right from the start, an architecture where the consuming project does not know _anything_ about Cmake, and it's entirely the responsibility of a producing project to wrap Cmake with variant aware dependency management so that the consumer cannot tell the difference between a Gradle C++ plugin built library and a cmake built library.

We want to evolve this into a series of samples, I think. Initially, I think it's ok to have a single Gradle app built against a single cmake built library, wired together in the same build. Later, we should reuse the pieces to show how this would work with binary dependencies, source dependencies, composite builds, Xcode, etc.

**Comment by ghale** [comment]
I think this is "done enough" to call this issue closed and handle any future improvements in separate issues.
