### ISSUE TITLE
Xcode plugin breaks configuration as it assumes all components will have a development binary defined

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#473]
If you apply `xcode` to all projects that have different sets of `operatingSystem`s, some projects will have components that are not buildable and will not have a development binary defined.  The Xcode plugin assumes that it can always get a development binary.

**Comment by ghale** [comment]
What is the expected behavior here (beyond not exploding during configuration)?  Should we look to make the behavior between Visual Studio and XCode consistent?  Some options:

1. We treat it like the "no c++ plugin applied" and generate an empty project (note that Visual Studio will not create a project at all when c++ is not applied).
1. We match the behavior of Visual Studio and don't create a project at all if no binaries exist.
1. We generate as much of the project as possible (lacking information that would come from the development binary).

2 seems most correct to me and we should change the behavior for "no c++/swift plugin applied" to match the Visual Studio behavior (i.e. it becomes the same as the "no binaries" case and we don't generate a project at all).  Thoughts?

**Comment by big-guy** [comment]
2 sounds fine to me

**Comment by adammurdoch** [comment]
For this issue, the behaviour should be whichever option is cheapest to implement while not blowing up at configuration time. #472 should take care of establishing a pattern for how the IDE plugins behave when things are missing, and issues should fork out of that to change the IDE plugins

**Comment by ghale** [comment]
Fair enough.  I think then option 1 is the cheapest solution - we can change it to be more consistent with the other plugins as a part of #472.

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/4602
