### ISSUE TITLE
Generate IDE projects for "buildable" binaries (software model)

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#507]
As a follow-up to #410

**Comment by ghale** [comment]
What we want to capture is that I don't want to generate metadata for binaries that I have explicitly modeled as not buildable.  Note that these are different from binaries that may not be buildable because the platform toolchain is not available.  We have at least one example of a use case where they want the metadata generated even though it can't be built on the local system (see #496).  This story deals with the case where a binary is explicitly disabled and will never be built anywhere (e.g. I never build static libraries for this component).  Given the two different use cases, we can't just say "only generate metadata for binaries that are buildable" as we don't currently have a way to distinguish between the two.

There are probably a couple of options here:

1. The simplest option would probably be to have the user specify on the extension whether or not metadata should be generated for non-buildable binaries.  This would probably just be a boolean flag on `VisualStudioExtension`.
1. We provide a flag on `VisualStudioProject` that states whether or not metadata should be generated.  Then a user can use something like `visualStudio.projects.matching { }` to disable projects that match some user-defined condition.
1. We do the same as above, but by default we disable projects whose binaries are all not buildable.  The user can then explicitly enable projects that have not-buildable binaries by creating a `visualStudio.projects.all { }` rule.
1. We somehow distinguish between a binary that has been explicitly disabled and a binary that should be buildable but isn't because an appropriate toolchain is not found.  We generate metadata for the former, but not the latter.

I feel like 3 is the option that is most likely going to be what everyone wants out-of-the-box but provides a simple escape hatch for users who need to generate metadata for non-buildable binaries.  Thoughts or other ideas?

**Comment by adammurdoch** [comment]
What's an "explicitly disabled" binary?

**Comment by ghale** [comment]
Where the user has done something like:

```
model {
  components {
    main {
      binaries.withType(StaticLibraryBinarySpec) {
        buildable = false
      }
    }
  }
}
```

**Comment by adammurdoch** [comment]
I would do whatever we do now, as that's a software model concern.

**Comment by ghale** [comment]
Ok, after discussing with @big-guy, we're not going to attempt to address the problem from #496 (i.e. "I want to sometimes generate metadata for non-buildable things") with this story, which makes this simple.  We'll only create projects/configurations for binaries that are buildable.

**Comment by ghale** [comment]
PR: https://github.com/gradle/gradle/pull/4549

@big-guy Can you take a look?

**Comment by ghale** [comment]
Merged
