### ISSUE TITLE
NullPointerException when parsing vswhere.exe output.

### ISSUE THREAD

**Issue by dorbeus** [gradle/gradle-native#508]
Just trying out the sample builds. but they all fail on windows because visual studio is not detected correctly.
used sample: native-samples/cpp/application.

I also would like you to add the "-prerelease" flag to vswhere so you can use the preview version of visual studio 2017

### Expected Behavior
A version of Visual studio should be detected  

### Current Behavior
* What went wrong:
A problem occurred configuring root project 'app'.
> Failed to notify project evaluation listener.
   > java.lang.NullPointerException (no error message)
   > No value has been specified for this provider.

### Context
Well unable to do builds on Windows...

### Steps to Reproduce (for bugs)
The new vswhere.exe discovery has never work on my setup.

### Your Environment

 * Build scan URL: 
https://gradle.com/s/p27uzjfkfcszy

vswhere.exe -all -legacy -format json
[
  {
    "instanceId": "489d52a4",
    "installDate": "2018-02-05T23:05:09Z",
    "installationName": "VisualStudio/15.5.6+27130.2027",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional",
    "installationVersion": "15.5.27130.2027",
    "productId": "Microsoft.VisualStudio.Product.Professional",
    "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\devenv.exe",
    "isPrerelease": false,
    "displayName": "Visual Studio Professional 2017",
    "description": "Professional developer tools and services for small teams",
    "channelId": "VisualStudio.15.Release",
    "channelPath": "C:\\Users\\m02ax102619pcadmin\\AppData\\Local\\Microsoft\\VisualStudio\\Packages\\_Channels\\4CB340F5\\catalog.json",
    "channelUri": "https://aka.ms/vs/15/release/channel",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660692#15.5.6",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660708",
    "catalog": {
      "buildBranch": "d15svc",
      "buildVersion": "15.5.27130.2027",
      "id": "VisualStudio/15.5.6+27130.2027",
      "localBuild": "build-lab",
      "manifestName": "VisualStudio",
      "manifestType": "installer",
      "productDisplayVersion": "15.5.6",
      "productLine": "Dev15",
      "productLineVersion": "2017",
      "productMilestone": "RTW",
      "productMilestoneIsPreRelease": "False",
      "productName": "Visual Studio",
      "productPatchVersion": "6",
      "productPreReleaseMilestoneSuffix": "0.0",
      "productRelease": "RTW",
      "productSemanticVersion": "15.5.6+27130.2027",
      "requiredEngineVersion": "1.14.192.55101"
    },
    "properties": {
      "campaignId": "",
      "channelManifestId": "VisualStudio.15.Release/15.5.6+27130.2027",
      "defaultProgram": "VisualStudio.489d52a4",
      "nickname": "",
      "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
    }
  },
  {
    "instanceId": "VisualStudio.14.0",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\",
    "installationVersion": "14.0"
  },
  {
    "instanceId": "VisualStudio.12.0",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\",
    "installationVersion": "12.0"
  }
]

**Comment by ghale** [comment]
I'm guessing this is the same as https://github.com/gradle/gradle/issues/4018.  Basically, it's failing because it's not finding the Visual Cpp installation.  In that issue, it was because the command line tools package was not installed.  Can you check that?

Regardless, the error handling here is poor and needs to be improved.  We've already created  https://github.com/gradle/gradle-native/issues/385 to improve this.

**Comment by dorbeus** [comment]
Hi
The C++/CLI that is mentioned dose not refer to a Command Line Interface.
In this case it refers to a managed c++ bastard used with the .net
framework.
https://en.wikipedia.org/wiki/C%2B%2B/CLI
So that should is not needed at all to compile real C++ code.
And yes I have installed it for just the sake and as expected, it did not
help.


2018-02-25 22:46 GMT+01:00 Gary Hale <notifications@github.com>:

**Comment by ghale** [comment]
OK, here is the sequence of steps Gradle goes through to set up the toolchain.  One of these is failing:

1. Execute vswhere to get the installationPath (in your case, this will be "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional".
1. Look for the Visual Cpp metadata file at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt", get the version of the compiler from there.
1. Look for the compiler installation at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\_VisualCppVersion_" where _VisualCppVersion_ is the version found in the previous step.

I'm guessing step 2 is failing.  Can you check that that file exists and if so, that the version it specifies corresponds to the Visual Cpp installation directory following the pattern above?

**Comment by dorbeus** [comment]
1. "installationPath": "C:\\Program Files (x86)\\Microsoft Visual
Studio\\2017\\Professional",
2. 14.12.25827
3. C:\Program Files (x86)\Microsoft Visual
Studio\2017\Professional\VC\Tools\MSVC\14.12.25827


Everything looks ok.


2018-02-27 13:28 GMT+01:00 Gary Hale <notifications@github.com>:

**Comment by Stevo-o** [comment]
I had the same problem and it turns out the problem was with an earlier version of visual studio and nothing to do with VS2017

The CommandLineToolVersionLocator tries to read the installs for every version reported by the vswhere.exe tool.

I had an old version VS2010 which was not installed correctly and the call to visualCppMetadataProvider.getVisualCppFromRegistry returned null because nothing was found in there.

Would a warning suffice if it fails to load metadata for a version which is not the latest.

**Comment by tonyabbott** [comment]
We've just seen what looks like the same NPE with Gradle 4.6. In our case, there was an old copy of VS2010 on the box that looks like it was partially uninstalled. Because Gradle enumerates all installed VS versions it was failing even though VS2010 was not required by our project. Fully uninstalling VS2010 solved the problem for us.

VS2010 was still being reported by vswhere.exe, but the registry keys that DefaultVisualCppMetadataProvider.getVisualCppFromRegistry() looks for were no longer present. It then returned null, and CommandLineToolVersionLocator.readInstall() doesn't handle a null return value from findVisualCppMetadata() properly, hence the NPE. I would think the appropriate behaviour would be to log a warning message and ignore that particular VS installation.

**Comment by ghale** [comment]
Thanks for the analysis @Stevo-o @tonyabbott!  We've got #385 to improve the messaging when we reject a candidate version, but I went ahead and created #570 to address this specific defect of blowing up when we come across this situation and handling the error more gracefully.

**Comment by czietsman** [comment]
I've got Visual Studio 2012 installed which has registry values under the key:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\SxS\VC7

I've also installed Visual Studio 2015 at some point which does **not** have registry values under that key.

It is however in the output for vswhere which is why it is returning null and failing the build.

![image](https://user-images.githubusercontent.com/396202/37141610-44b0914a-22be-11e8-83bc-b48b617bacc0.png)

![image](https://user-images.githubusercontent.com/396202/37141593-30357e1a-22be-11e8-8031-ad7fc39e08bd.png)

![image](https://user-images.githubusercontent.com/396202/37141632-5b4fde1a-22be-11e8-8a29-e2d779e532da.png)

![image](https://user-images.githubusercontent.com/396202/37141689-8223bf48-22be-11e8-9970-38125ee4964d.png)
