### ISSUE TITLE
MSBuild executor is terribly slow with InProcessGradleExecuter

### ISSUE THREAD

**Issue by ghale** [gradle/gradle-native#613]
Compare this: https://builds.gradle.org/project.html?projectId=Gradle_Check_Platform_Java8_Oracle_Windows&testNameId=-1488513902405588142&tab=testDetails

To this: https://builds.gradle.org/project.html?tab=testDetails&testNameId=-1488513902405588142&projectId=Gradle_Check_Quick_Java7_Oracle_Windows&buildTypeId=Gradle_Check_Quick_Java7_Oracle_Windows_ideNative

For some reason, when running with the `InProcessGradleExecuter`, these msbuild tests are _extremely_ slow.

**Comment by ghale** [comment]
A little more information - MSBuild seems to be spending the time in executing the gradle build even though the gradle build seems to complete fairly quickly (using "/v:diag" option to MSBuild):

```
...
Task Performance Summary:
        0 ms  FindAppConfigFile                          2 calls
        2 ms  SetEnvironmentVariable                     2 calls
        2 ms  AssignProjectConfiguration                 2 calls
        6 ms  Message                                    5 calls
        7 ms  SetEnv                                     8 calls
        8 ms  MakeDir                                    4 calls
       16 ms  ResolvePackageFileConflicts                2 calls
       29 ms  ResolveAssemblyReference                   2 calls
    266599 ms  Exec                                       2 calls
    267155 ms  MSBuild                                    3 calls

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileMainWin32DebugSharedLibraryMainCpp
> Task :linkMainWin32DebugSharedLibrary
> Task :mainWin32DebugSharedLibrary

BUILD SUCCESSFUL in 8s
2 actionable tasks: 2 executed


Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileMainWin32DebugStaticLibraryMainCpp
> Task :createMainWin32DebugStaticLibrary
> Task :mainWin32DebugStaticLibrary

BUILD SUCCESSFUL in 7s
2 actionable tasks: 2 executed
```

**Comment by big-guy** [comment]
@lacasseio I think I fixed it: https://github.com/gradle/gradle/commit/bad53f5122079bc9d25418c642a2a75351d6a26d

The difference between forkingIntegTest and integTest is the type of Gradle executor the test uses. In the msbuild tests, when we use the forking executor, the test starts a build to generate the VS metadata, which forks a daemon, and then the test runs msbuild.  Since the daemon is not a direct child of msbuild, the test finishes quickly.

When the same tests run with the embedded executor, the test generates the VS metadata in the test process (no daemon is involved) and when the test runs msbuild, Gradle needs to fork a daemon at that time.  msbuild sees the Gradle daemon still running and waits for it to timeout (2 minutes).  We run Gradle multiple times in a single msbuild invocation, so this can take a long time.

My fix is to force the VS metadata generation to also use a daemon, so the daemon is already started by the time we run msbuild.

Could you verify that we don't see the same kind of timeout when VS starts the daemon? e.g., something like:

- gradle visualStudio
- gradle --stop
- open visual studio and run build

**Comment by lacasseio** [comment]
I don't have yet an actual fix except than finding another way to write the code to redirect the command line output into files. It seems through some weird chain of events we may be hitting what seems to be a [bug in MSBuild](https://github.com/Microsoft/msbuild/issues/3383).

The issue is it doesn't happen all the time. If we invoke the command straight (Gradle wrapper) there isn't any problem. If we remove the output redirection to files, again, there isn't an issue. It's when the [code is as it is right now](https://github.com/gradle/gradle/commit/4e3ea5b2dc16a52cdc564aee8bcca52fe3557c80).

**Comment by big-guy** [comment]
To be clear with what Daniel wrote above, this doesn't happen if you use the generated VS metadata as-is with msbuild or VS.  It's only a problem with our tests because we redirect the output from the Gradle process to separate files (so we can scrape them later).

I think since this only happens through our test infrastructure and we have a workaround (start the daemon before msbuild), we can consider this done.
