### ISSUE TITLE
Profiling with older Groovy build scripts

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#619]

**Comment by ghale** [comment]
The purpose of this work was to see if the effect on build times with lazy tasks is greater with primarily groovy-based build scripts rather than Kotlin.  To do so, I grabbed Gradle 4.5.1 (which has primarily groovy build scripts) and modified the scripts to take advantage of lazy tasks.  I was able to get it to 1393 lazy tasks that were avoided compared to 3015 total tasks (46% of all tasks avoided creation/configuration).   

If anyone is interested in what I had to do to convert the build scripts, take a look at https://github.com/gradle/gradle/compare/v4.5.1...gh/lazy-tasks/legacy-gradle.  The changes themselves were fairly simple in most cases, but the bulk of the work was in simply finding the places where we were causing unnecessary realization of tasks.

I haven't done as exhaustive an analysis as we did for the [Kotlin-based Gradle build](https://github.com/gradle/gradle-native/issues/602#issuecomment-383155092), but we do see a significant improvement for Groovy-based builds which appears to be even better than that for Kotlin-based builds.

Measurements were gathered using the gradle-profiler benchmark and running `gradle help` with 10 warmups and 20 iterations. We are seeing the following improvements to overall build time:

tasks avoided | % tasks avoided | Mean Improvement | Minimum Improvement
---------------- | ---------------- | ------------------- | ----------------------- 
887 | 29% | 4.75% | 1.25% | 0.80%
1393 | 46% | 17.79% | 15.54% | 13.31%

What we can see from above is that even at roughly half of the tasks being avoided, we're already seeing almost 20% improvement in configuration time.  Another interesting thing to note is that there is a big jump between 29% of tasks and 46% of tasks, which shows that there isn't a linear improvement in the number of tasks whose configuration is avoided - it matters which task configuration blocks are being avoided.  We obviously made some very juicy config blocks lazy in that second batch of changes and that improved our config time substantially.  This should not be a surprise, but it should color these numbers some.  If we avoided 90% of tasks, that would not necessarily mean that we would shave of 35% of config time - it would always depend on the cost of the tasks that were avoided.

The raw numbers from these tests are here: 

https://docs.google.com/spreadsheets/d/1iOZS4ALDXGpaGSrPvYSFOq06bKvi-a-28RMLOtXbpuQ/edit?usp=sharing
