### ISSUE TITLE
Ensure lazy task API is convenient to use from Kotlin DSL

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#626]
Do whatever work is required to make the API added in #606 convenient to use from Kotlin DSL, if anything. Ideally, this would be handling general purpose patterns in Kotlin DSL rather than an ad hoc solution for the lazy task API.

The lazy task API should also be convenient to use from a plugin implemented using Kotlin, if this more or less just happens to work as well.

**Comment by big-guy** [comment]
Notes about idiomatic Kotlin tasks:
https://github.com/gradle/kotlin-dsl/blob/develop/samples/task-dependencies/build.gradle.kts
https://github.com/gradle/kotlin-dsl/issues/34#issuecomment-272172389

We want to add a `TaskProvider TaskCollection.get(String)` (and add this to all container types), but this conflicts with Kotlin's `get(String)` extension it adds to containers so that you can use array-style access (e.g., `tasks["compileJava"]`).  

We need to work this out with Kotlin DSL, for now, we only have a `get(Class, String)` method.

**Comment by big-guy** [comment]
Review with Kotlin DSL team when ready

**Comment by big-guy** [comment]
This looks good to me after playing around with it in gradle/gradle.  We have #814, #815, #816, #821 for some follow up things we can do.
