### ISSUE TITLE
Rework ArchivePublishArtifact to not use an eagerly created AbstractArchiveTask

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#644]
This blocks `jar` from using the lazy task API because `ArchivePublishArtifact` uses the jar task directly.

**Comment by ghale** [comment]
So, I’ve found the problem with the gradle/gradle build.  The problem is that when we realize a lazy task through the `TaskCreatingProvider`, we don’t remove it from the pending store.  This means that it if we then remove the task, it can still be re-created when iterating over the collection or something similar.

A simple fix would be to just have `TaskCreatingProvider` remove the provider from the backing store when the provider is realized.  However, this issue is symptomatic of the underlying problem which is that the contract of `DomainObjectCollection` allows you to add any sort of `Provider` and handles removing it from the pending store as part of its operations, but makes no guarantees about what happens if that `Provider` is realized outside of the collection.  

There's probably a couple of options here:

1. Leave it as is and let any `Provider` somehow handle things itself (e.g. the `Provider` has some hook into the pending store outside of `DomainObjectCollection` such as being created by `DefaultTaskContainer`).
1. Provide some semantics on `DomainObjectCollection` where a `Provider` (or user of the provider) can manage this itself.  For instance, an `unregister()` method to remove a provider from the collection.
1. Disallow any type of `Provider` and require a known type of provider.  For instance, `DomainObjectCollection` only allows providers of a certain type that are created by the collection and are guaranteed to do the appropriate things to clean it up in the pending store when realized.  Seems like this could also be implemented as some sort of generic decoration around an existing provider.
1. Another approach altogether would be to just clean it up after the fact - i.e. the next time we try to access the `Provider` through the pending store, we simply ignore it (and remove it) if it is already realized.  This would probably also require a special type of provider that can tell us if it's realized or not.

There might be other options I'm not thinking about right now.  I think I'm going to proceed with the "simple fix" for now (since the only place we're really using this stuff right now is tasks) but I'd appreciate feedback (or other ideas) on the options above for a longer term solution.

**Comment by big-guy** [comment]
Seems like this makes #710 more important too.  

On the gradle/gradle side, is there something better we could do in the build that wouldn't require removing the jar task?

**Comment by lacasseio** [comment]
I remember when fixing the remove case with 4.8, I played around that removing a task would also search for the registered provider and remove them as well. I didn't push the code as we settle on fixing it differently but that could be another way to fix this. However, this would only work for the named containers. We won't be able to solve this for the `DomainObjectCollection`. Disallowing external `Provider` could be a great way to go for now but that would limit the use case for the lazy API in order context outside of `Task` creation.

I see this as fixing `TaskCreatingProvider` is 1 day vs disallowing is multi-day vs a generic option is a week. At this very instant, we could just do the quick fix. For lazy task configuration, I think we only need disallowing to make sure no one shoots themselves in the foot.

**Comment by ghale** [comment]
Instead of removing the task, I think we can just check to see if there's a default artifact or not.

**Comment by adammurdoch** [comment]
Sounds like there are 3 separate issues here:

1. The `gradle/gradle` build removes a task. This is always a bad idea and we should change the build to not do this, regardless of what we choose to do with the other 2 issues.
2. `remove()` does not work when used with a task defined using `register()`. We should fix `remove()` so that it works with a task that has not been realised and fails with a task that has.
3. Tasks that aren't managed by the task container can be added using `addLater(Provider)` and `add(Task)` and `addAll(Collection<Task>)`. We want the task container to own the lifecycle of every tasks it contains, so it should be an error to call any of these methods on a task container. However, in general, it should be entirely possible to add a calculated value to a container (i.e. add something to a collection of `T` using a `Provider<T>`), so we shouldn't remove the method and it should still work in general on a `DomainObjectCollection`.
