### ISSUE TITLE
How to locate and use a local Boost installation?

### ISSUE THREAD

**Issue by DanielSWolf** [gradle/gradle-native#648]
*First of all, sorry for not using the issue template. It did't seem a good fit for a question like this. If there's a better place to ask this question, please let me know.*

I have a C++ project that uses CMake, and I'm considering migrating to Gradle. The one thing that keeps me from migrating is support for locating the Boost libraries.

In addition to the header-only Boost libraries, my project also uses some Boost libraries that require compilation. CMake comes with a module named [FindBoost](https://cmake.org/cmake/help/v3.8/module/FindBoost.html). You tell it what version and what kind build you need (static or dynamic libs, static or dynamic C++ runtime, single-threaded or multi-threaded...). The plugin then automatically finds a matching local Boost installation (by looking at `BOOST_ROOT` etc.). Within that installation, it finds the library files that match the specified configuration.

Using FindBoost, my CMake-based build automatically finds the correct Boost libraries on any platform (Windows/Mac/Linux).

Does Gradle have a similar mechanism? How would I setup a Gradle project that automatically finds the correct local Boost installation and uses the libraries with the correct configuration?

**Comment by lacasseio** [comment]
Thanks @DanielSWolf for this question/issue. At the moment, we don't yet have an excellent solution to solve this problem. This issue is already tracked by https://github.com/gradle/gradle-native/issues/380 which I encourage you to follow and comment your use case. We are looking at adding a similar capability for any prebuilt library installed on your system. Until then, you would have to resort to a custom plugin making the same discovery.

I also encourage you to look at the [native samples](https://github.com/gradle/native-samples) which demonstrate common use case with Gradle. With regards to holding the migration to Gradle, you can start using Gradle today by [merely wrapping CMake](https://github.com/gradle/native-samples/tree/master/cpp/cmake-library). Then, you can piece out the part of the build that doesn't require feature provided out of the box by CMake. Once the prebuilt library support makes its way to the core of Gradle, you can migrate the last part, or you can write a custom plugin that searches for the right Boost binaries.

Thanks for the question. You can use the [Gradle user forum](https://discuss.gradle.org/) for such question in the future.
