### ISSUE TITLE
Spike improvements to `gradle tasks` and IDE import without fully configuring tasks

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#692]

**Comment by adammurdoch** [comment]
We have 2 approaches to this:

- Improve IDE sync so that it becomes less monolithic. For example, make it easier for the IDE to ask for the dependencies model without realizing all of the tasks, and separately ask for the details of the task. This lines up with the direction we're taking with IDE sync in general.
- Add some kind of new API for build logic to define the description and group proeprties of a task without triggering the full configuration, plus an API to query this. IDE sync can use this new API.

I think we should aim to do the first option, as it enables other improvements to IDE sync not related to task realization, while keeping the task API simpler.
