### ISSUE TITLE
Tasks created by Rules cannot be found via lazy APIs

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#718]
given:
```
apply plugin: 'java'

tasks.named("uploadArchives").configure {
    println "hello!"
}
```
This fails with the message:
```
> Task with name 'uploadArchives' not found in root project 'lazy-upload'.
```

We have `upload`, `clean` and `build` rules built in.

**Comment by big-guy** [comment]
Document this as a known issue

**Comment by eskatos** [comment]
While working on https://github.com/gradle/kotlin-dsl/issues/907 I stumbled upon this in our `maven` plugin sample.

The `maven` plugin relies on task rules to register the `Upload` tasks. Making it impossible to lazily configure them. We changed our sample to eagerly configure instead as a work around.

**Comment by adammurdoch** [comment]
Instead of adding a workaround to the sample, we should change the maven plugin to listen for the creation of configurations and register an upload task placeholder (to keep things backwards compatible).

Then, we can later change the maven plugin to use the public API that we add to lazily add elements a container that are derived from the elements of another container, and perhaps also add a public API that allows the plugin to keep the 'register this task only if not known' behaviour.

**Comment by big-guy** [comment]
PR: https://github.com/gradle/gradle/pull/6250

I also found and raised a new issue https://github.com/gradle/gradle/issues/6249

This becomes annoying if you're trying to be "type safe" and do things like `tasks.withType(JavaCompile).named("compileJava")`.  I suspect that since this has been broken for a long time, people don't really do this with tasks created by rules.
