### ISSUE TITLE
Make gradle/gradle build completely lazy

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#727]
- Using the new API in buildSrc and in gradle/gradle's build scripts

It's OK if a 3rd party plugin still uses eager API

**Comment by lacasseio** [comment]
This is mostly done, the build is not completely lazy because of various issues such as lazy configurations with rules. However, everywhere should be using the lazy task configuration. The next step would be to hunt down where the laziness isn't happening by adding the reporting capability in Gradle. This should be considered as a separate issue.

**Comment by etiennestuder** [comment]
@lacasseio Were build scans helpful during the migration process?

**Comment by lacasseio** [comment]
For this work, we focused on converting eager API usage with lazy API. Where the build scan could excel is giving information regarding where each task gets realized. From there, it would be easy to hunt down where tasks get unnecessarily realized. We could even do some automation and report where a task got resolved and didn't participate in the task execution graph construction. Those would be the actual problem to solve.

**Comment by etiennestuder** [comment]
@lacasseio I propose you get in touch with @tomdcc who implemented the support in build scans to make sure you fully leverage what we currently offer and to learn from you what is missing.

**Comment by lacasseio** [comment]
A discussion will be done as part of issue https://github.com/gradle/gradle-native-private/issues/131.

**Comment by big-guy** [comment]
can we make a list of issues for the remaining bits of work? third party plugins, etc.

**Comment by lacasseio** [comment]
### Highest creation count
- 519 tasks from `buildSrc` (some not converted, but they are all used in `buildSrc`)
- 268 tasks from `org.owasp.dependencycheck` plugin
- 151 tasks from `me.champeau.gradle.jmh` plugin

### Known issues
- 94 tasks form `java` plugin (`jar` task)
- 16 tasks from `gradlebuild.performance-test` plugin (8 caused by [unable lazily configure a task rule](https://github.com/gradle/gradle-native/issues/718), 8 others requires more troubleshooting)
- 3 tasks from `subprojects/distributions/distributions.gradle` script (seems to be related to artifacts DSL block)
- 1 tasks from `subprojects/base-services/base-services.gradle.kts` script (may be caused by `jar` tasks)
- 1 tasks from `subprojects/docs/docs.gradle` script (`css` tasks provider resolved to be used in the artifacts DSL block)
- 28 tasks from `kotlin` plugin

### Hard to troubleshoot issues
- 16 tasks from `gradle/shared-with-buildSrc/code-quality-configuration.gradle.kts` script
- 13 tasks from `checkstyle` plugin
- 13 tasks from `codenarc` plugin
- 4 tasks from `distribution` plugin (also some unconverted tasks)
- 3 tasks from `gradlebuild.test-files-cleanup` plugin
- 3 tasks from `subprojects/native/native.gradle` script
- 3 tasks from `org.gradle.kotlin.dsl.provider.plugins.KotlinScriptBasePlugin` plugin
- 3 tasks from `org.gradle.kotlin.dsl.plugins.precompiled.PrecompiledScriptPlugins`  plugin
- 1 tasks from `subprojects/tooling-api/tooling-api.gradle.kts` script
- 1 task from `gradlebuild.shaded-jar` plugin

### Tasks used in `buildSrc`
- 50 tasks from `java-gradle-plugin` plugin (not converted and used in `buildSrc`)
- 3 tasks from `org.gradle.kotlin.dsl.plugins.precompiled.PrecompiledScriptPlugins` plugin (not converted and used in `buildSrc`)

### Not converted
- 12 tasks from `maven` plugin (not converted)
- 2 tasks from `application` plugin (not converted)
- 1 tasks from `org.asciidoctor.gradle.asciidoctor` plugin (not converted)

**Comment by lacasseio** [comment]
The most impactful at the moment are 3rd party plugins and `buildSrc` tasks which is kind of normal unless we have an idea to avoid `buildSrc` execution.

**Comment by eskatos** [comment]
Latest of `org.gradle.kotlin.dsl.provider.plugins.KotlinScriptBasePlugin` already uses lazy task configuration.

`org.gradle.kotlin.dsl.plugins.precompiled.PrecompiledScriptPlugins` will be tackled soon in https://github.com/gradle/kotlin-dsl/issues/951
