### ISSUE TITLE
Disallow the use of hooks such as afterEvaluate() by a lazy configuration action

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle-native#734]
A lazy configuration action should mutate only the subject of the action and project and build level hooks almost always configure something else. A lazy configuration action should also make no assumptions about timing and the use of afterEvaluate() assumes that the action runs before this hook, which will not necessarily be the case.

Calling `afterEvaluate()` from a lazy configuration action should be an error. Based on feedback, we might look at overloads or other methods to allow a lazy configuration action to make explicit what it assumes to have already happened and not yet happened when the action runs, and Gradle can make sure that this is the case (or fail).

**Comment by big-guy** [comment]
Need to document this behavior as different from the existing API because some configuration blocks do not run all of the time.

**Comment by lacasseio** [comment]
Here is a spike: https://github.com/gradle/gradle/pull/6003

**Comment by ghale** [comment]
@lacasseio It kind of feels like this should be managed by a service or ThreadLocal or something so that things that want to check this state (i.e. whether or not they are executing from a lazy block) can do so without needing access to the `TaskContainer`.  For instance, if we want to catch this in build level hooks, it won't be clear which task container should be checked.

It might make sense to enumerate some of the places where we might want to do this, and then formulate a consistent approach that can be used everywhere.

**Comment by lacasseio** [comment]
Thanks for the good feedback, I will make the required modification.

**Comment by lacasseio** [comment]
@ghale I converted the protection logic into a service and made it more general (aka not specific to Lazy Task API). Can you do another quick code review just to see if I'm going in the right direction? I'm also pretty bad regarding naming classes, if you have suggestion, don't hesitate to comment.

**Comment by adammurdoch** [comment]
For now, we should only prevent access to the hooks from a configuration action. Everything else should be a separate issue.
