### ISSUE TITLE
Introduce `MapProvider` to fill the gap in the Provider API

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle-native#746]
### Expected Behavior

Can use `Provider<Map>` and `Property<Map>`

### Current Behavior

Need to use a plain `Map`.

### Context

See https://gradle.slack.com/archives/C03A0MT6S/p1530599441000061 and https://github.com/gradle/gradle/pull/5183#discussion_r199475152

### Your Environment

 * Build scan URL:

**Comment by marcphilipp** [comment]
There's already an implementation by @tbroyer which me might (should he agree) be able to reuse, if applicable:
https://github.com/tbroyer/gradle-errorprone-plugin/blob/76407271db78c535337c7aa9238fdaf75229b447/src/main/java/net/ltgt/gradle/errorprone/DefaultMapProperty.java

**Comment by mkobit** [comment]
+1 to this - I have some awkward usage of `SetProperty<Map.Entry<A, B>>` which is wonky and difficult to use. From the `kotlin-dsl` perspective, an extension that takes in a `Pair` would also be helpful.

**Comment by tbroyer** [comment]
> There's already an implementation by @tbroyer which we might (should he agree) be able to reuse, if applicable

This code is under Apache License, feel free to copy/reuse (I'm not sure it'd be the best approach though). I also haven't fully thought it through; take it more like an experiment (like using a `ListProperty<CommandLineArgumentProvider>` rather than a `List<CommandLineArgumentProvider>`). For example, should the user be able to add a `Provider<Map.Entry<K, V>>`? a `Map.Entry<K, Provider<V>>`? both?

As said in https://github.com/gradle/gradle/pull/5183#discussion_r199475152, my main driver is to use a `Property`/`Provider` instead of _convention mapping_, all while keeping the `Map` incrementally _buildable_ (in this specific case, compiler options as key-value pairs), which a `Property<Map<K, V>>` doesn't (easily) allow. Given my current API (with specific methods allowing to add entries in the maps), I could actually use different implementations internally, and only expose a `Property<Map<K, V>>` (to be future-proof, like the case of properties in `MavenPomDeveloper` and `MavenPomContributor`).

**Comment by lacasseio** [comment]
This has been introduced in Gradle 5.1. Open any issue regarding missing features on [`gradle/gradle`](https://github.com/gradle/gradle).
