### ISSUE TITLE
Duplicate lib Windows SDK library used at link time when both SDK8 & SDK10 are installed

### ISSUE THREAD

**Issue by zosrothko** [gradle/gradle-native#85]
Hi

Building the native-binaries/cpp project with both SDK 8.1 & SDK 10 installed, gradle 4.01 includes the 
2 SDK x86 lib directory in the LIBPATH while only one should be used, as show by the output.txt
```
/DEBUG
/OUT:C:\Users\fandre\Documents\git\gradle\subprojects\docs\src\samples\native-binaries\cpp\build\libs\hello\shared\hello.dll
/NOLOGO
/DLL
"/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib"
"/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x86"
"/LIBPATH:C:\Program Files (x86)\Windows Kits\10\Lib\10.0.15063.0\ucrt\x86"
C:\Users\fandre\Documents\git\gradle\subprojects\docs\src\samples\native-binaries\cpp\build\objs\hello\shared\helloCpp\aqkdip9r4oh0soue6oadhmiqw\hello.obj
```

C:\Users\fandre\Documents\git\gradle\subprojects\docs\src\samples\native-binaries\cpp>gradlew -version

------------------------------------------------------------
Gradle 4.0.1
------------------------------------------------------------

Build time:   2017-07-07 14:02:41 UTC
Revision:     38e5dc0f772daecca1d2681885d3d85414eb6826

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_80 (Oracle Corporation 24.80-b11)
OS:           Windows 8.1 6.3 amd64

**Comment by lacasseio** [comment]
Thanks @zosrothko for this issue. The work to solve this issue will most likely be tackled with [the more generalized way of defining SDKs](https://github.com/gradle/gradle-native/issues/86#issuecomment-322618081).

**Comment by big-guy** [comment]
@ghale can you see if this is an issue still?

**Comment by ghale** [comment]
@zosrothko So this is happening because we currently automatically add a windows sdk onto the lib path and, in previous versions of Gradle, we were not capable of discovering a windows 10 sdk.  So Gradle was looking for a windows sdk (any windows sdk) and finding the highest version that it could comprehend (windows 8.1 sdk).  So what you're seeing on the path there is the windows 10 UCRT (required by Visual Studio 2017) and then the windows 8.1 sdk (automatically discovered).

With Gradle 4.3, there is support for discovering windows 10 sdks, so what you would see in this scenario is both the UCRT and SDK being discovered for windows 10.

In the future, we also want to make this more declarative and remove the logic that blindly adds a windows sdk onto the lib path.  So when you define your component, you would also declare something to the effect of "this component needs windows 8.1 sdk" or "this component needs windows 10 sdk" and we would find an appropriate sdk that met your requirements.  If you did not declare anything, then we would just not add any windows sdk onto the lib path.

I believe this resolves the reported issue (with the release of Gradle 4.3).  If you feel like it does not, let me know and we can re-open.
