### ISSUE TITLE
User can supply a settings.gradle file for non-Gradle source dependencies

### ISSUE THREAD

**Issue by eljobe** [gradle/gradle-native#89]
When specifying a VCS repository which an be built instead of consuming a binary artifact from Maven, the user can also specify a settings.gradle file to configure whatever build logic is needed by Gradle to build the project being checked out. This allows Gradle to know about dependencies that are not yet converted to Gradle and build them. At this point, Gradle would only support building direct source dependencies. Transitive dependencies will come later.

This should include an updated sample.

We need to decide if we want to fail or allow consumers to overwrite an existing `settings.gradle`.

### Test coverage
- I should be able to specify a settings file in Groovy or Kotlin that describes the structure of the build and applies built-in plugins.
- I should be able to apply plugins from an external repository to the build script.
- Changes to the settings file should be reflected in the source dependencies without having to delete/repopulate the checkout directory.
### Out of scope
- Modifying/moving/patching/etc existing files (see #334)

**Comment by big-guy** [comment]
We need to keep in mind that not all `settings.gradle` will be `settings.gradle` (some will be `settings.gradle.kts`): https://github.com/gradle/gradle/pull/3120#issuecomment-335480499

**Comment by big-guy** [comment]
# Injectable configuration for source dependencies

## Use cases

1. Source dependency does not provide any build configuration.
1. Source dependency provides build configuration, but it needs to be extended.
1. Source dependency provides build configuration, but it needs to be replaced.

For current Swift work, primarily need #1. #3 may be rare enough that it could be ignored.

There are two aspects of this feature:
1. Providing/sharing the configuration for the source dependency
1. Describing how to find #1

For #1, we could provide complete files that are intended to replace or be "added" to existing configuration (literally appended or just applied separately). We could also restrict the source of configuration to only "plugin-like" things (e.g., plugins from the plugin portal).

For #2, we could provide a DSL to describe where to find #1 or we could force this on the user by requiring the user to provide something like an init script.

All of these options below have a couple of common questions:
- What does it mean to provide configuration for a multi-project mapping?
- How do we detect "different" configuration when the same repo may be used by multiple mappings, but not necessarily a multi-project build?

## Just give me the files

```
sourceControl {
    vcsMappings {
        withModule("org.test:dep") {
            from vcs(GitVersionControlSpec) {
                url = "git://..."
                configurationDir = file("config/dep")
            }
        }
    }
}
```

Inside `config/dep`, we provide all of the appropriate settings and build script files. 

Pros:
- Clear where the configuration comes from
- Separate configuration directory can be treated as a complete project, so things like uto-complete should just work.
- Configuration can be in Groovy DSL or Kotlin DSL or include more complicated things like buildSrc
Cons:
- Unwieldy with lots of mappings 
- Reuse must be local unless we provide a way to share the configuration via a new mechanism
- Unclear how a generic wrapper could come out of this

--------------------------------------------------------------------------------

## Restricted "give me the files" - Only provide a settings file via Resource

```
sourceControl {
    vcsMappings {
        withModule("org.test:dep") {
            from vcs(GitVersionControlSpec) {
                url = "git://..."
                settingsFile = resources.text.fromString '''
                    rootProject.name = "dep"
                '''
                // Alternative
                settingsFile = resources.text.fromFile(file("dep-settings.gradle"))
            }
        }
    }
}
```

Pros:
- Easy to provide a script for the settings file without any setup
- Can share/generate settings file in place (via string interpolation)
Cons:
- Unwieldy with lots of mappings 
- Reuse must be local or via remote HTTP scripts
- Unclear how auto-complete would work with the provided settings
- Applying external plugins to projects from settings file seems to be broken
- How do we select which DSL language to use? settings.gradle vs settings.gradle.kts?
Additional notes:
- We could also provide a `buildFile` resource.

--------------------------------------------------------------------------------

## Providing configuration via a plugin

```
sourceControl {
    vcsMappings {
        withModule("org.test:dep") {
            from vcs(GitVersionControlSpec) {
                url = "git://..."
                plugins {
                    id "dep-configuration"
                    id "external-thing" version "2.0"
                }
            }
        }
    }
}
```

Pros:
- Forces configuration into a separate, shareable thing from the start
- If the configuration is a separate thing, auto-complete/normal plugin lifecycle is available
- Doesn't require us to force a particular DSL language 
Cons:
- Harder to get going? Rodrigo script plugin->binary plugin work helps here, but is Kotlin only.
- Is this too much like `plugins {}`, but completely different?
- Where are these plugins applied--settings, build file, or both?
Questions:
- What's the source of the plugins? Can a user configure different sources?

--------------------------------------------------------------------------------

## Diversion: treating repository as a separate top-level thing

This is related to the questions/options above.  Let's just assume configuration is handled by `magicMethod()`. In this change, VCS mappings would no longer be able to create new repositories.  They could only refer to existing ones.


```
sourceControl {
    repositories {
        dep(GitVersionControlSpec) {
            url = "git://..."
            magicMethod()
        }
    }
    vcsMappings {
        withModule("org.test:dep") {
            from repositories.dep
        }
        withModule("org.test:anotherSubproject") {
            from repositories.dep
        }
    }
}
```

Pros:
- VCS source information (URL, configuration magic) kept in one place
- Enforcing duplication rules or detecting duplicates could be easier
Cons:
- `repositories` isn't quite the right word
- Overly verbose?  What else would use this repository information?

--------------------------------------------------------------------------------

## Proposal

None of the choices feel great. I like the simplicitly of just providing configuration directly, but it lets people do anything in an environment where we can't help them much. It also makes the "extend only" use case harder.

I think providing just a list of plugins to apply is too restrictive.

I think separating the VCS repository into its own container seems like a worthwhile change on its own. I don't think we need to do that for this change, but we should do it soon after.

My proposal would be for something that looks like this (drops `Resource` and just uses plain `File`s):

```
sourceControl {
    vcsMappings {
        withModule("org.test:dep") {
            from vcs(GitVersionControlSpec) {
                url = "git://.../dep"
                buildFile = file("path/to/something.gradle")
                settingsFile = file("path/to/dep-settings.gradle")
            }
        }
    }
}
```

Where `buildFile` and `settingsFile` contain configuration that is combined with any existing configuration.  Maybe `additionalBuildFile` or something would be a better name.

After cloning a repository, if `settingsFile` is defined, we will inject the equivalent of:
```
apply from: $settingsFile
```

If no `settingsFile` is defined and no settings file exists, we can just generate an empty file.

If `buildFile` is defined, we will inject the equivalent of `apply plugin: $buildFile` or a plugin request for a plugin named `$buildFile` (based on the auto-binary plugin work).

We could make it so `buildFile` and `settingsFile` could be downloaded from another source. If the configuration is ultimately coming from a binary plugin from a repository, we could make it easier to put the configuration to locate the binary plugin directly in the mapping. This would move us back closer to the Resource option above.

Thoughts on the above @adammurdoch @ghale @lacasseio ?

**Comment by adammurdoch** [comment]
I'd vote strongly for using plugins and not files. Reuse is the most common case for this feature, or really _the_ use case for this feature. A major con for providing a settings or build script is that it is yet another way to package up build logic for reuse. We want fewer mechanisms, not more, so that we can end up with a single mechanism that works well in a cross cutting way. And we already have a mechanism for reuse that works well enough for what we need in our plugin infrastructure.

> Harder to get going? Rodrigo script plugin->binary plugin work helps here, but is Kotlin only.

I'm not sure. You can put the implementation in `buildSrc` as a groovy source file.

If you like, that plugin can go looking for files in conventional locations or remote locations to apply to the source dependency build. Or whatever it wants. This convention plugin can then evolve from there, moving to another repo and being released from there.

We might consider an example plugin or even a built-in plugin that does this.

> Is this too much like plugins {}, but completely different?

I'm not sure what the con here is. It is just a set of plugins to apply to some other build, similar to what a `plugins { }` block in the settings script of the target build would do. The only difference is _who_ gets to say. In this instance, it's the main build rather than the source dependency build, which is what we want.

> Where are these plugins applied--settings, build file, or both?

To the settings of the target build. The plugin can then do whatever it likes, including applying other plugins to the projects of the build.

> What's the source of the plugins? Can a user configure different sources?

It would be the source of any plugins that is visible to the main build, which currently happens to be anything in `buildSrc`, anything in the `pluginManagement { }` block. Later, it would include any other sources we add, such as the conveniences for local binary plugins and so on.

**Comment by ghale** [comment]
Good write-up of the options, @big-guy 

> Is this too much like plugins {}, but completely different?

I'm with @adammurdoch here - I don't think this is a con at all.  Instead, I think it leverages the user's existing understanding of that dsl and minimizes what they have to learn to use this productively.

> We might consider an example plugin or even a built-in plugin that does this.

I think a simple example would probably be enough to get people going if they just wanted to have a bunch of scripts in a directory.

> I think providing just a list of plugins to apply is too restrictive.

What do you think makes that restrictive?  The fact that they have to write a plugin to extend the other build?  Or is there another aspect of it that bothers you?

I certainly agree that there will be cases where someone only wants to make a minor change to an external build and a plugin might be a lot of ceremony for something like that, but I think there's a lot of value in the use case of "I want to bring this thing in that is not a gradle build and wrap gradle configuration around it" and being able to support that _and make it reusable_ is huge.  I like the idea of pushing it down the path of reusability from the start.

**Comment by bamboo** [comment]
> I certainly agree that there will be cases where someone only wants to make a minor change to an external build and a plugin might be a lot of ceremony for something like that.

I'd be very interested in exploring a little more what might qualify as too much ceremony here in the context of the work we're doing to simplify the definition of binary plugins.

For instance, would it be too much ceremony to require the following structure for a plugin that augments the external build with a local plugin repository?

```kotlin
// buildSrc/build.gradle.kts
plugins {
  // `kotlin-dsl` automagically exposes `*.gradle.kts` scripts as binary plugins 
  `kotlin-dsl` 
}

// buildSrc/src/main/kotlin/plugin-repositories.settings.gradle.kts
// Automagically exposed as a Settings plugin with id "plugin-repositories"
pluginManagement {
  repositories {
   maven(url = "https://artifactory:8080/m2/")
  }
}
```

The first plugin would require two files, `build.gradle.kts` and the plugin itself but after that first step, defining a new plugin becomes as simple as creating a `gradle.kts` file under the conventional source directory.

Your thoughts?

**Comment by big-guy** [comment]
> > I think providing just a list of plugins to apply is too restrictive.

> 
> What do you think makes that restrictive? The fact that they have to write a plugin to extend the other build? Or is there another aspect of it that bothers you?

It's not the ceremony around making a plugin that bothers me. It's that if we call it `plugins {}`, we have to mirror the implementation of `plugins {}` (which is an AST/extraction sort of thing) and I think we may want it to behave differently (e.g., allow for variables? shared configuration across vcs mappings, etc). I think we can also do auto-complete from the real `plugins {}`, but if I'm really modifying the source dependency's build, we don't know the complete configuration yet.

I hadn't considered making the main build's configuration the source of the source dependency's configuration (expose its buildSrc and plugin management configuration). The other thing that bothered me is if we don't share configuration like that, there isn't a way to specify custom `pluginManagement {}` unless we add that too.  At that point, we're creating a constrained DSL that looks a lot like `Settings`.

@bamboo I think your suggestion is focusing on the "how do I configure the build?" side of things. I think we all agree that should always be done via binary plugins. What you've put here looks reasonable to me.

The confusing part for me is after we have `buildSrc` (or external plugins published to a plugin portal), how do we describe "apply plugin _foo_ to this source dependency"? This can't be a plugin because we're back to the same question (how do I apply _foo applying_ plugin to this source dependency?)

I'll type up a modified proposal.

**Comment by bamboo** [comment]
Thanks for clarifying, @big-guy.

About:

> we have to mirror the implementation of plugins {} (which is an AST/extraction sort of thing)

I don't think we would have to mirror the Groovy AST/extraction logic for that to work. We could execute the `plugins` block against a custom `PluginDependenciesSpec` implementation that captures the relevant data like it's done [here](https://github.com/gradle/kotlin-dsl/blob/8ec17e0efef56108830c4299393e4d22fb2b26d6/gradle/plugins/plugins.gradle.kts#L41) with an API like:

```java
interface GitVersionControlSpec {
...
    void plugins(Action<PluginDependenciesSpec> block);
...
}
```

That way all the `kotlin-dsl` extensions to the plugins DSL based on`PluginDependenciesSpec` and `PluginDependencySpec` would just work.

**Comment by big-guy** [comment]
Thanks @bamboo, I didn't know about that!

Based on the comments above, I'll modify my proposal to the other option:

```
sourceControl {
    vcsMappings {
        withModule("org.test:dep") {
            from vcs(GitVersionControlSpec) {
                url = "git://.../dep"
                plugins {
                    ...
                }
            }
        }
    }
}
```

With these implementation details:
- The included builds will inherit the "plugin management" configuration from their parent build.
- `buildSrc` will be added to the included build's buildscript classpath
- We'll collect the plugin dependencies in `plugins {}` and inject those as requests in the included build.

Plugins will be expected to implement `Plugin<Settings>` and be expected to apply other plugins (defined in `buildSrc` or elsewhere).

I think it would still be worthwhile to eventually migrate to something like this:
```
sourceControl {
    repositories {
        dep(GitVersionControlSpec) {
            url = "git://.../dep"
            plugins {
                ...
            }
        }
    }
    vcsMappings {
        withModule("org.test:dep") {
            from repositories.dep
        }
    }
}
```

This makes the VCS mapping "dumber" since it can only point to an existing repository and not create a new one.

**Comment by big-guy** [comment]
There's a dirty hack to make this work, https://github.com/gradle/gradle/commits/sg/native/vcs-settings-plugins

It's not safe to use yet, but I'm detangling the plugin application/resolver/plugin-use so I can inject the plugins in a reasonable way (vs my hardcoded hacking).

**Comment by big-guy** [comment]
@adammurdoch I'll fix the CI failures, but any major comments for?
 https://github.com/gradle/gradle/pull/3878
