### ISSUE TITLE
Demonstrate native build using architecture

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle-native#920]
We should fix our use of this in google-test build and its consuming project.

**Comment by andreiled** [comment]
How do I get Gradle to build for multiple target machines _at once_ when there are multiple target machines binaries for which can be built on current build machine?

When I try to configure my own custom platform & machine in addition to the standard platforms, Gradle seem to build only for the first target machine matching the build machine where I expect it to build for both target machines at once.
I know that my own custom platform & machine are configured correctly since Gradle builds for them just fine when I comment out the standard list of target machines in `build.gradle`.
